### ISSUE TITLE
Mejoras en la movilidad del personaje

### ISSUE THREAD

**Issue by maria-angslz** [TheBandicoots/2018_1_K3011_TheBandicoots#7]
El robot mueve mucho los brazos y las piernas y se mueve demasiado lento al presionar las teclas.

**Comment by nico-abram** [comment]
Asumo que sliding (Mas los cambios a las velocidades de rotacion/movimiento/salto de Mauro), el correcto angulo inicial y el arreglo a las animaciones ya arreglaron esto
